export const QUICKSAND_LIGHT = 'QUICKSAND_LIGHT';
export const QUICKSAND_REGULAR = 'QUICKSAND_REGULAR';
export const QUICKSAND_MEDIUM = 'QUICKSAND_MEDIUM';
export const QUICKSAND_SEMI_B = 'QUICKSAND_SEMI_B';
export const QUICKSAND_BOLD = 'QUICKSAND_BOLD';
